### PR TITLE
Update zer0dump.py

### PR DESCRIPTION
**Pull request by 3v4Si0N**
If the domain admin user was not administrator the reset of the DC password did not work

### CODE REVIEW

**Comment by bb00** [comment]
You do understand that a domain admin user by definition has to be an administrator, right?

Or is there something I’m misunderstanding about your issue; please provide a bit of context.

**Comment by bb00** [comment]
Oh, read your changes. I made a simple mistake. Allow me to fix that within the next few minutes.

**Comment by bb00** [comment]
Fixed. Thank you for your feedback.

**Comment by 3v4Si0N** [comment]
Yes, of course. But, if you choose another user to dump the NTLM hash, the reset doesn't work because the hash you use to reset is the one that has been dump.

**Pull request closed without merging**
